version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    executor:
      name: android/android-docker
      tag: 2024.01.1
    steps:
      - checkout
      - run:
          name: Create local.properties
          command: echo "sdk.dir=/opt/android/sdk" > local.properties
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug
      - android/save-gradle-cache
      - android/save-build-cache
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk
      - persist_to_workspace:
          root: app/build/outputs/apk/debug/
          paths:
            - '*.apk'

workflows:
  build-and-test:
    jobs:
      - build
